Integration specs for views and fix n+1 problems
muhammedb8826/blog-app pull request #13
Opened 2023-07-05 21:37 UTC by muhammedb8826

### In this Milestone we have worked on the following:

N + 1 Improvements

User#index before

<img width="652" alt="user index before" src="https://github.com/muhammedb8826/blog-app/assets/115731485/27ca8353-d0fa-4887-a7d6-78dcf1318291">

User#index after

<img width="709" alt="user index after" src="https://github.com/muhammedb8826/blog-app/assets/115731485/b3585d87-3def-4b2b-b224-6259ae1952bb">

User#show before

<img width="711" alt="user show before" src="https://github.com/muhammedb8826/blog-app/assets/115731485/a8a965ab-6541-42f7-9894-01eede9f634c">

User#show after

<img width="714" alt="user show after" src="https://github.com/muhammedb8826/blog-app/assets/115731485/d43a91a7-af78-4191-a637-7a07cabe6e47">

- User index page:

I can see the username of all other users.
I can see the profile picture for each user.
I can see the number of posts each user has written.
When I click on a user, I am redirected to that user's show page.

- user show page:

I can see the user's profile picture.
I can see the user's username.
I can see the number of posts the user has written.
I can see the user's bio.
I can see the user's first 3 posts.
I can see a button that lets me view all of a user's posts.
When I click a user's post, it redirects me to that post's show page.
When I click to see all posts, it redirects me to the user's post's index page.

- User post index page:

I can see the user's profile picture.
I can see the user's username.
I can see the number of posts the user has written.
I can see a post's title.
I can see some of the post's body.
I can see the first comments on a post.
I can see how many comments a post has.
I can see how many likes a post has.
I can see a section for pagination if there are more posts than fit on the view.
When I click on a post, it redirects me to that post's show page.

- Post show page:

I can see the post's title.
I can see who wrote the post.
I can see how many comments it has.
I can see how many likes it has.
I can see the post body.
I can see the username of each commentor.
I can see the comment each commentor left.

- All the tests passing

![all the tests are passed](https://github.com/muhammedb8826/blog-app/assets/115731485/34bd07e4-93da-4adf-967b-b9d80d04f014)

2023-07-05 22:26 UTC, codepantha requested changes
# STATUS: CHANGES REQUIRED ♻️

## Hi team 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media4.giphy.com/media/rZ10JtoPRv1Ly/giphy.gif"/>

## Highlights 🎯 
✔️ Descriptive PR
✔️ Written integration tests 📌 
✔️ No linter errors

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- n/a

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-05 22:26 UTC, codepantha commented on spec/integration/user_show_spec.rb
> +  end
- [ ] There are 2 tests shown below that are missing in your `user_show_spec.rb` file. Please write them as they compulsory requirements 👍 
![image](https://github.com/muhammedb8826/blog-app/assets/46839548/6aefec6c-baf7-41c4-850d-b12db1e00a37)

2023-07-05 22:26 UTC, codepantha commented on spec/integration/posts_index_spec.rb
> +  end
- [ ] Please write a test that asserts you can see the user's profile picture 👍

2023-07-05 22:26 UTC, codepantha commented on spec/integration/user_index_spec.rb
> +    end
- [ ] In the testing requirements for the User index page, it is expected that you write tests that assert an expected outcome for all users - not a single user as you have done here. Please see the requirements below and adjust each of your test to cater to all the users 🙏 
![image](https://github.com/muhammedb8826/blog-app/assets/46839548/38628f38-1dfc-4180-af1b-9664be7ac731)

2023-07-06 00:18 UTC, Reem-lab approved these changes
# Hi @muhammedb8826,  👋🏻👋🏻

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media2.giphy.com/media/3GBG7xejOXhH7MyQkn/giphy.gif"/>

## Highlights

- [ ] No Linters errors 🔥
- [ ]  Great job working on the functionality of the tests💯
- [ ]  Followed Gitflow 🔥
- [ ] Kudos for working on the requested changes 💯🤩

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-06 15:18 UTC, merged